# Generated by Django 5.1.1 on 2024-10-14 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, help_text="创建时间"),
        ),
        migrations.AlterField(
            model_name="room",
            name="is_active",
            field=models.BooleanField(default=False, help_text="是否激活"),
        ),
        migrations.AlterField(
            model_name="room",
            name="is_attachment",
            field=models.BooleanField(default=False, help_text="是否为附件房间"),
        ),
        migrations.AlterField(
            model_name="room",
            name="name",
            field=models.CharField(help_text="房间名", max_length=255),
        ),
        migrations.AlterField(
            model_name="room",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, help_text="更新时间"),
        ),
        migrations.AlterField(
            model_name="room",
            name="user",
            field=models.ForeignKey(
                help_text="用户id",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(auto_created=True, help_text="时间"),
                ),
                ("content", models.TextField(help_text="消息内容")),
                ("role", models.CharField(help_text="角色", max_length=20)),
                ("model", models.CharField(help_text="模型", max_length=20)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="用户id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
